import { StyleSheet } from "react-native";
import { ColorPalette } from "../../constants/Colors";

export const getStyles = (colors: ColorPalette) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.surfaceLowest },
    kav: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceHigh,
      //backgroundColor: "#f5f6f7eb",
      gap: 10,
    },
    backBtn: { padding: 4 },
    headerInfo: { flex: 1, minWidth: 0 },
    headerName: { fontSize: 16, fontWeight: "500", color: colors.onSurface },
    headerHandle: { fontSize: 14, fontWeight: "500", color: colors.primary },
    headerSub: { fontSize: 13, color: colors.onSurfaceVariant, marginTop: 1 },
    headerActions: { flexDirection: "row", gap: 2 },
    headerBtn: { padding: 8, borderRadius: 10 },
    messageList: { paddingHorizontal: 12, paddingVertical: 12 },
    typingRow: { paddingHorizontal: 16, paddingVertical: 4 },
    typingText: { fontSize: 11, color: colors.primary, fontStyle: "italic" },
    inputBar: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: colors.surfaceHigh,
    flexDirection: "row",
      alignItems: "center",
      position:"fixed",
      gap: 8,
      borderRadius: 28,
      width:"100%",
 
      // backgroundColor: "#f5f6f7eb",
    },
    mediaPreview: {
      marginBottom: 8,
      alignSelf: "flex-start",
      position: "relative",
    },
    mediaThumb: {
      width: 90,
      height: 90,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    mediaRemove: {
      position: "absolute",
      top: -8,
      right: -8,
      backgroundColor: colors.error,
      borderRadius: 12,
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 28,
      backgroundColor: colors.surfaceLow,
      width: "80%"

    },
    attachBtn: { padding: 4, paddingBottom: 6, opacity: 0.5, marginBottom: -2 },
    textInput: {
        fontSize: 18,
        color: colors.onSurface,
        flex: 1,
      maxHeight: 120,
      paddingVertical: 6,
        backgroundColor: colors.surfaceLow,
         paddingHorizontal: 14,
        borderRadius: 28,
    },
    sendBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 2,
    },
    sendBtnDisabled: { opacity: 0.4 },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    emptyText: { fontSize: 15, color: colors.onSurfaceVariant },

    recordingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 12,
    },
    recordActionBtn: {
      padding: 6,
    },
    recordingIndicator: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    recordingDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#EF4444",
    },
    recordingTimer: {
      fontSize: 15,
      fontWeight: "600",
    },
  });
