export const SOCKET_RECONNECT_INITIAL_DELAY = 1000;

export const SOCKET_RECONNECT_MAX_DELAY = 30000;

export const SOCKET_HEARTBEAT_INTERVAL = 30000;

export const SOCKET_CONNECTION_TIMEOUT = 10000;

export const SOCKET_MAX_QUEUE_SIZE = 500;